version: "3"
services:
  backend:
    build:
      context: ./backend
    hostname: backend
    restart: always
    container_name: backend
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./backend:/backend
  frontend:
    build:
      context: ./frontend
    hostname: frontend
    restart: always
    container_name: frontend
    ports:
      - 3000:3000
